kind: pipeline
type: kubernetes
name: default

steps:
- name: test
  image: alpine
  commands:
  - echo "Hello from Drone CI!"
  - echo "Build number is $DRONE_BUILD_NUMBER"
  - echo "Commit is $DRONE_COMMIT_SHA"
