kind: pipeline
type: kubernetes
name: default

steps:
  - name: install
    image: node:20-alpine
    commands:
      - apk add --no-cache git
      - npm ci

  - name: build
    image: node:20-alpine
    commands:
      - apk add --no-cache git
      - npm run docs:build

  - name: deploy
    image: plugins/gh-pages
    settings:
      netrc: true
      pages_directory: docs/.vitepress/dist
      target_branch: gh-pages
    when:
      branch:
        - main
      event:
        - push

trigger:
  branch:
    - main
  event:
    - push
    - pull_request
